baseURL = "https://cloudnativegeo.org"
title = "Cloud-Native Geospatial Forum - CNG"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
relativeURLs = true

[pagination]
  pageSize = 10

[params]
  description = "Where geospatial data users create the future together."
  copyright = "Copyright © 2024 Radiant Earth"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "home"
    pageref = "/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    pageref = "/about"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    pageref = "/blog"
    weight = 15

  [[menu.main]]
    identifier = "join"
    name = "join"
    title = "join CNG"
    pageref = "/join"
    weight = 20

  [[menu.main]]
    identifier = "events"
    name = "events"
    title = "events"
    pageref = "/events"
    weight = 25

  [[menu.main]]
    identifier = "guide"
    name = "guide"
    title = "guide"
    url = "http://guide.cloudnativegeo.org"
    weight = 40
    [menu.main.params]
      external = true

[permalinks]
  blog = "blog/:year/:month/:slug/"
  events = "events/:slug/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true

[imaging]
  # Use cached images and don't reprocess unless source changes
  disableHugoDefaults = false
  quality = 80
  anchor = "Smart"
